In [33]:
import pandas as pd
import requests
from itertools import chain   
import requests
import numpy as np

def scrap_last_update():
    


    l= []   
    
    for i in range(0,661,60):
        
       
        name = 'https://sofifa.com/teams?type=club&showCol%5B0%5D=ti&showCol%5B1%5D=oa&showCol%5B2%5D=at&showCol%5B3%5D=md&showCol%5B4%5D=df&showCol%5B5%5D=tb&showCol%5B6%5D=bs&showCol%5B7%5D=bd&showCol%5B8%5D=bp&showCol%5B9%5D=bps&showCol%5B10%5D=cc&showCol%5B11%5D=cp&showCol%5B12%5D=cs&showCol%5B13%5D=cps&showCol%5B14%5D=da&showCol%5B15%5D=dm&showCol%5B16%5D=dw&showCol%5B17%5D=dd&showCol%5B18%5D=dp&showCol%5B19%5D=ip&showCol%5B20%5D=ps&showCol%5B21%5D=sa&offset=' + '%02d' % i 


        r1 = requests.get(name)
        

        l.append(pd.read_html(r1.content))

        print('appended ',i)    
        
    df= pd.concat(chain.from_iterable(l))
    
    
    return(df)

In [34]:
df = scrap_last_update()

appended  0
appended  60
appended  120
appended  180
appended  240
appended  300
appended  360
appended  420
appended  480
appended  540
appended  600
appended  660

In [36]:
pd.set_option('display.max_columns', None)

df.head()

,Unnamed: 0,Name,ID,OVA,ATT,MID,DEF,Transfer Budget,Speed,Dribbling,Passing,Positioning,Crossing,Passing.1,Shooting,Positioning.1,Aggression,Pressure,Team Width,Defender Line,DP,IP,Players,SAA,Hits
0,NaN,Liverpool English Premier League (1),9,85,89,84,86,€90M,Slow,Little,Short,Organised,Little,Safe,Little,Organised,Contain,Deep,Narrow,Cover,9,10,33,26.73,3.3K
1,NaN,Manchester City English Premier League (1),10,85,86,86,83,€176M,Slow,Little,Short,Organised,Little,Safe,Little,Organised,Contain,Deep,Narrow,Cover,10,9,33,27.00,1.6K
2,NaN,Real Madrid Spain Primera Division (1),243,85,84,86,85,€188.5M,Slow,Little,Short,Organised,Little,Safe,Little,Organised,Contain,Deep,Narrow,Cover,10,10,30,27.64,2.7K
3,NaN,FC Bayern München German 1. Bundesliga (1),21,84,91,85,82,€100M,Slow,Little,Short,Organised,Little,Safe,Little,Organised,Contain,Deep,Narrow,Cover,10,10,23,26.82,2.1K
4,NaN,FC Barcelona Spain Primera Division (1),241,84,84,85,83,€180.5M,Slow,Little,Short,Organised,Little,Safe,Little,Organised,Contain,Deep,Narrow,Cover,10,10,33,27.82,4.2K

In [40]:
df.info

<bound method DataFrame.info of     Unnamed: 0                                              Name      ID  OVA  \
0          NaN              Liverpool English Premier League (1)       9   85
1          NaN        Manchester City English Premier League (1)      10   85
2          NaN            Real Madrid Spain Primera Division (1)     243   85
3          NaN        FC Bayern München German 1. Bundesliga (1)      21   84
4          NaN           FC Barcelona Spain Primera Division (1)     241   84
..         ...                                               ...     ...  ...
16         NaN   Sligo Rovers Rep. Ireland Airtricity League (1)     563   58
17         NaN  Shelbourne FC Rep. Ireland Airtricity League (1)     834   57
18         NaN      Cork City Rep. Ireland Airtricity League (1)     422   57
19         NaN     Finn Harps Rep. Ireland Airtricity League (1)  111131   56
20         NaN   Waterford FC Rep. Ireland Airtricity League (1)     753   55

    ATT  MID  DEF Transfer Budget Speed Dribbling Passing Positioning  \
0    89   84   86            €90M  Slow    Little   Short   Organised
1    86   86   83           €176M  Slow    Little   Short   Organised
2    84   86   85         €188.5M  Slow    Little   Short   Organised
3    91   85   82           €100M  Slow    Little   Short   Organised
4    84   85   83         €180.5M  Slow    Little   Short   Organised
..  ...  ...  ...             ...   ...       ...     ...         ...
16   59   56   58           €515K  Slow    Little   Short   Organised
17   57   57   57           €520K  Slow    Little   Short   Organised
18   55   58   55           €600K  Slow    Little   Short   Organised
19   54   56   57           €500K  Slow    Little   Short   Organised
20   55   55   55           €520K  Slow    Little   Short   Organised

   Crossing Passing.1 Shooting Positioning.1 Aggression Pressure Team Width  \
0    Little      Safe   Little     Organised    Contain     Deep     Narrow
1    Little      Safe   Little     Organised    Contain     Deep     Narrow
2    Little      Safe   Little     Organised    Contain     Deep     Narrow
3    Little      Safe   Little     Organised    Contain     Deep     Narrow
4    Little      Safe   Little     Organised    Contain     Deep     Narrow
..      ...       ...      ...           ...        ...      ...        ...
16   Little      Safe   Little     Organised    Contain     Deep     Narrow
17   Little      Safe   Little     Organised    Contain     Deep     Narrow
18   Little      Safe   Little     Organised    Contain     Deep     Narrow
19   Little      Safe   Little     Organised    Contain     Deep     Narrow
20   Little      Safe   Little     Organised    Contain     Deep     Narrow

   Defender Line  DP  IP  Players    SAA  Hits
0          Cover   9  10       33  26.73  3.3K
1          Cover  10   9       33  27.00  1.6K
2          Cover  10  10       30  27.64  2.7K
3          Cover  10  10       23  26.82  2.1K
4          Cover  10  10       33  27.82  4.2K
..           ...  ..  ..      ...    ...   ...
16         Cover   5   1       25  24.27    23
17         Cover   4   1       24  25.91    26
18         Cover   7   2       25  23.91    35
19         Cover   2   1       25  26.36    26
20         Cover   4   1       21  24.18    59

[681 rows x 25 columns]>